"""MiniCPM5 的 JEV/TypeSafe 风格 System One 受限决策引擎 (批量推理核心).

对外只暴露三块:
- template: 官方对话模板渲染 (绝不手搓 ChatML / 裸文本) 与 EntryType 序列化;
- labels: 受限决策标签组与组间受限 softmax;
- chunking: 候选分块规划与跨块 log-odds 对齐 (候选数不受限);
- engine: 批量推理引擎, 一次 llama_decode 处理整批序列, 只在决策位读 logits.
"""

from .chunking import (
    DEFAULT_CHUNK_SIZE,
    MAX_CHUNK_SIZE,
    Chunk,
    ChunkAlignError,
    ChunkPlan,
    align_chunks,
    chunk_log_odds,
    global_softmax,
    plan_chunks,
)
from .decision import (
    MAX_SCORE_LEVELS,
    MIN_SCORE_LEVELS,
    Answer,
    Choice,
    ChoiceAnswer,
    Noul,
    NoulAnswer,
    Question,
    QuestionError,
    Score,
    ScoreAnswer,
    Usage,
    answer,
    answer_all,
    answer_choice,
    answer_noul,
    answer_score,
    normalized_peak,
    parse_question,
    weighted_level_score,
)
from .runtime import (
    DEFAULT_N_CTX,
    MAX_N_CTX,
    BatchEngine,
    Device,
    EngineConfig,
    EngineError,
    acquire_device,
    reset_device_lock,
    validate_n_ctx,
)
from .labels import (
    BOOL_LABEL_SPECS,
    NONE_LABEL,
    LabelResolutionError,
    LabelSet,
    LabelSpec,
    NumericLabels,
    label_texts,
    resolve_labels,
)
from .template import (
    ChatTemplateError,
    EntryTypeError,
    get_chat_template,
    is_entry,
    render_chat,
    render_entry,
)

__all__ = [
    "BOOL_LABEL_SPECS",
    "BatchEngine",
    "ChatTemplateError",
    "Chunk",
    "ChunkAlignError",
    "ChunkPlan",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_N_CTX",
    "Device",
    "EngineConfig",
    "EngineError",
    "EntryTypeError",
    "LabelResolutionError",
    "LabelSet",
    "LabelSpec",
    "MAX_CHUNK_SIZE",
    "MAX_N_CTX",
    "MAX_SCORE_LEVELS",
    "MIN_SCORE_LEVELS",
    "NONE_LABEL",
    "NumericLabels",
    "Answer",
    "Choice",
    "ChoiceAnswer",
    "Noul",
    "NoulAnswer",
    "Question",
    "QuestionError",
    "Score",
    "ScoreAnswer",
    "Usage",
    "acquire_device",
    "align_chunks",
    "answer",
    "answer_all",
    "answer_choice",
    "answer_noul",
    "answer_score",
    "chunk_log_odds",
    "get_chat_template",
    "global_softmax",
    "is_entry",
    "label_texts",
    "normalized_peak",
    "parse_question",
    "plan_chunks",
    "render_chat",
    "render_entry",
    "resolve_labels",
    "reset_device_lock",
    "validate_n_ctx",
    "weighted_level_score",
]
